export const PatientsActionTypes = {
  SET_CURRENT_PATIENT: 'SET_CURRENT_PATIENT',
  FETCH_PATIENTS_START: 'FETCH_PATIENTS_START',
  FETCH_PATIENTS_SUCCESS: 'FETCH_PATIENTS_SUCCESS',
  FETCH_PATIENTS_FAILURE: 'FETCH_PATIENTS_FAILURE',
}
